import Head from 'next/head';
import { useState } from 'react';
import { getTrip, ItineraryItem } from '../lib/getTrip';
import styles from '../styles/Home.module.css';

const Dropdown = ({
  options,
  value,
  onChange,
  label,
}: {
  options: string[];
  value: string;
  label: string;
  onChange;
}) => {
  return (
    <div
      style={{
        width: '100%',
      }}
    >
      <label htmlFor={label}>{label}</label>
      <select
        id={label}
        value={value}
        onChange={onChange}
        style={{
          display: 'block',
          padding: '10px 12px 10px 12px',
          borderRadius: '8px',
          border: 'none',
          width: '100%',
        }}
      >
        {options.map((e) => (
          <option value={e} key={e}>
            {e}
          </option>
        ))}
      </select>
    </div>
  );
};

const Input = ({
  value,
  onChange,
  label,
}: {
  value: string;
  onChange;
  label: string;
}) => {
  return (
    <div
      style={{
        width: '100%',
      }}
    >
      <label htmlFor={label}>{label}</label>
      <div style={{ padding: 3 }} />
      <input
        id={label}
        value={value}
        onChange={onChange}
        style={{
          display: 'block',
          padding: '10px 12px 10px 12px',
          borderRadius: '8px',
          border: 'none',
          width: '100%',
        }}
      />
    </div>
  );
};

const Spacer = () => {
  return <div style={{ padding: 10 }} />;
};

export default function Home() {
  const [country, setCountry] = useState('');
  const [travelStyle, setTravelStyle] = useState('');
  const [duration, setDuration] = useState('');
  const [age, setAge] = useState('');
  const [tripDescription, setTripDescription] = useState('');
  const [itinerary, setItinerary] = useState<ItineraryItem[]>([]);
  const [queryState, setQueryState] = useState<
    'error' | 'loading' | 'success' | 'none'
  >('none');

  const handleButtonClick = async () => {
    if (!country || !travelStyle || !duration || !age) {
      alert('fill out all fields');
      return;
    }
    setQueryState('loading');
    const res = await getTrip({ country, travelStyle, age, duration });
    if (res) {
      setQueryState('success');
      setTripDescription(res.tripDescription || '');
      setItinerary(res.itinerary || []);
      return;
    }
    setQueryState('error');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ maxWidth: 400, margin: 'auto' }}>
        <h1 className={styles.title}>Choose a trip</h1>
        <Spacer />
        <Input
          value={age}
          onChange={(e) => setAge(e.target.value)}
          label={'Age'}
        />

        <Spacer />
        <Input
          value={duration}
          onChange={(e) => setDuration(e.target.value)}
          label={'Duration of trip'}
        />

        <Spacer />
        <Dropdown
          options={['', 'italy', 'china']}
          value={country}
          onChange={(e) => setCountry(e.target.value)}
          label="Country"
        />
        <Spacer />

        <Dropdown
          options={['', 'active', 'comfort']}
          value={travelStyle}
          onChange={(e) => setTravelStyle(e.target.value)}
          label="Travel Style"
        />
        <Spacer />
        <Spacer />
        <button
          onClick={handleButtonClick}
          style={{ padding: '10px 10px 10px 10px', borderRadius: '8px' }}
        >
          Send
        </button>
        {queryState === 'loading' && <p>Loading...</p>}
        {queryState === 'success' && (
          <div>
            <div>
              <h2>Trip Description</h2>
              <p>{tripDescription}</p>
            </div>
            <div>
              <h3>Itinerary</h3>
              {itinerary.map((e) => (
                <div key={e.name}>
                  <h4>{e.name}</h4>
                  <p>{e.description}</p>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
